In [13]:
import numpy as np
from sklearn import preprocessing,  neighbors
from sklearn.model_selection import train_test_split
import pandas as pd

In [17]:
df= pd.read_csv('breast-cancer-wisconsin.data')
df.replace('?', -9999, inplace=True)
df.drop(['id'], 1 , inplace=True)
df

C:\Users\Emirhan\AppData\Local\Temp/ipykernel_17304/2082391533.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df.drop(['id'], 1 , inplace=True)


clump_thickness   unif_cell_size  unif_cell_shape  marg_adhesion  \
0                  5                1                1              1   
1                  5                4                4              5   
2                  3                1                1              1   
3                  6                8                8              1   
4                  4                1                1              3   
..               ...              ...              ...            ...   
694                3                1                1              1   
695                2                1                1              1   
696                5               10               10              3   
697                4                8                6              4   
698                4                8                8              5   

     single_epith_cell_size bare_nuclei  bland_chrom  norm_nucleoli  mitoses  \
0                         2           1            3              1        1   
1                         7          10            3              2        1   
2                         2           2            3              1        1   
3                         3           4            3              7        1   
4                         2           1            3              1        1   
..                      ...         ...          ...            ...      ...   
694                       3           2            1              1        1   
695                       2           1            1              1        1   
696                       7           3            8             10        2   
697                       3           4           10              6        1   
698                       4           5           10              4        1   

     class  
0        2  
1        2  
2        2  
3        2  
4        2  
..     ...  
694      2  
695      2  
696      4  
697      4  
698      4  

[699 rows x 10 columns]

In [30]:
x=np.array(df.drop(['class'],1))
y=np.array(df['class'])
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2)
classifier=neighbors.KNeighborsClassifier()
classifier.fit(x_train,y_train)
accuracy=classifier.score(x_test, y_test)
print(accuracy)
print(x_train)

0.9785714285714285
[[5 3 3 ... 3 4 1]
 [5 10 10 ... 7 10 1]
 [3 1 1 ... 3 1 1]
 ...
 [6 10 7 ... 8 10 2]
 [3 10 3 ... 5 1 4]
 [10 3 5 ... 3 5 3]]


C:\Users\Emirhan\AppData\Local\Temp/ipykernel_17304/2884193794.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x=np.array(df.drop(['class'],1))


In [36]:
example_measures= np.array([[4,1,1,1,1,2,3,4,1]])
#example_measures= example_measures.reshape(len(example_measures),-1)
prediction=classifier.predict(example_measures)
print(prediction)

[2]
